import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { SafeAreaView } from "react-native-safe-area-context";

import { Card, Pill, SectionTitle } from "../../src/ui/components";
import { colors } from "../../src/ui/theme";

function GoalCard({ title, amount, target, progress, icon, tone }: { title: string; amount: string; target: string; progress: string; icon: keyof typeof MaterialCommunityIcons.glyphMap; tone: string }) {
  return <Card style={styles.goal}><View style={[styles.goalIcon, { backgroundColor: `${tone}18` }]}><MaterialCommunityIcons color={tone} name={icon} size={24} /></View><View style={styles.goalContent}><View style={styles.goalTitleRow}><Text style={styles.goalTitle}>{title}</Text><Pill label={progress} tone="success" /></View><Text style={styles.goalAmount}>{amount} <Text style={styles.goalTarget}>sur {target}</Text></Text><View style={styles.rail}><View style={[styles.fill, { backgroundColor: tone, width: progress }]} /></View><Text style={styles.goalNote}>Prochaine étape : 50 000 FCFA ce mois</Text></View><MaterialCommunityIcons color={colors.textMuted} name="chevron-right" size={23} /></Card>;
}

export default function Savings() {
  return <SafeAreaView edges={["top"]} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>VOS PROJETS</Text><Text style={styles.title}>Épargne</Text></View><Pressable style={styles.addButton}><MaterialCommunityIcons color="#FFFFFF" name="plus" size={22} /></Pressable></View>
    <Card style={styles.total}><View><Text style={styles.totalLabel}>Total mis de côté</Text><Text style={styles.totalAmount}>1 240 000 <Text style={styles.totalCurrency}>FCFA</Text></Text><Text style={styles.totalCopy}>Vous avancez avec régularité. Continuez ainsi.</Text></View><View style={styles.totalIcon}><MaterialCommunityIcons color="#FFFFFF" name="piggy-bank-outline" size={30} /></View></Card>
    <SectionTitle action="Voir l'historique" title="Vos objectifs" />
    <View style={styles.goals}><GoalCard amount="840 000 FCFA" icon="car-outline" progress="42 %" target="2 000 000" title="Fonds voiture" tone={colors.primary} /><GoalCard amount="250 000 FCFA" icon="beach" progress="25 %" target="1 000 000" title="Vacances" tone={colors.accent} /></View>
    <SectionTitle title="Votre rythme" />
    <Card><View style={styles.rhythmHeader}><View style={styles.rhythmIcon}><MaterialCommunityIcons color={colors.success} name="trending-up" size={24} /></View><View style={styles.rhythmCopy}><Text style={styles.rhythmTitle}>En bonne voie</Text><Text style={styles.rhythmText}>Votre rythme est supérieur de 12 % à votre objectif mensuel.</Text></View></View><View style={styles.dashes}>{[0, 1, 2, 3, 4, 5].map((item) => <View key={item} style={[styles.dash, item < 4 && styles.dashActive]} />)}</View><View style={styles.rhythmFooter}><Text style={styles.rhythmFooterText}>120 000 FCFA ce mois</Text><Text style={styles.rhythmFooterText}>Objectif 105 000</Text></View></Card>
    <Pressable style={styles.contribute}><MaterialCommunityIcons color="#FFFFFF" name="plus-circle-outline" size={20} /><Text style={styles.contributeText}>Ajouter à mon épargne</Text></Pressable>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  addButton: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 15, height: 44, justifyContent: "center", width: 44 }, contribute: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 17, flexDirection: "row", gap: 9, justifyContent: "center", marginTop: 26, paddingVertical: 16 }, contributeText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, content: { padding: 20, paddingBottom: 32 }, dash: { backgroundColor: colors.border, borderRadius: 4, flex: 1, height: 8 }, dashActive: { backgroundColor: colors.success }, dashes: { flexDirection: "row", gap: 5, marginTop: 20 }, eyebrow: { color: colors.textMuted, fontSize: 11, fontWeight: "800", letterSpacing: 0.8 }, fill: { borderRadius: 4, height: "100%" }, goal: { alignItems: "center", flexDirection: "row", gap: 12, padding: 15 }, goalAmount: { color: colors.text, fontSize: 14, fontWeight: "800" }, goalContent: { flex: 1, gap: 7 }, goalIcon: { alignItems: "center", borderRadius: 14, height: 47, justifyContent: "center", width: 47 }, goalNote: { color: colors.textMuted, fontSize: 11 }, goalTarget: { color: colors.textMuted, fontSize: 12, fontWeight: "500" }, goalTitle: { color: colors.text, fontSize: 15, fontWeight: "800" }, goalTitleRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, goals: { gap: 10 }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, rail: { backgroundColor: colors.surfaceMuted, borderRadius: 4, height: 7, overflow: "hidden" }, rhythmCopy: { flex: 1, gap: 3 }, rhythmFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 9 }, rhythmFooterText: { color: colors.textMuted, fontSize: 11 }, rhythmHeader: { alignItems: "center", flexDirection: "row", gap: 12 }, rhythmIcon: { alignItems: "center", backgroundColor: colors.successSoft, borderRadius: 14, height: 47, justifyContent: "center", width: 47 }, rhythmText: { color: colors.textMuted, fontSize: 12, lineHeight: 18 }, rhythmTitle: { color: colors.text, fontSize: 15, fontWeight: "800" }, safeArea: { backgroundColor: colors.background, flex: 1 }, title: { color: colors.text, fontSize: 25, fontWeight: "800", marginTop: 4 }, total: { alignItems: "center", backgroundColor: colors.text, borderColor: colors.text, flexDirection: "row", justifyContent: "space-between", marginTop: 24, padding: 20 }, totalAmount: { color: "#FFFFFF", fontSize: 25, fontWeight: "800", marginTop: 5 }, totalCopy: { color: "#C9D1DF", fontSize: 12, marginTop: 8 }, totalCurrency: { fontSize: 13 }, totalIcon: { alignItems: "center", backgroundColor: colors.accent, borderRadius: 17, height: 58, justifyContent: "center", width: 58 }, totalLabel: { color: "#C9D1DF", fontSize: 13, fontWeight: "700" },
});
